# Generated by Django 4.1.7 on 2023-02-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Название")),
                ("number", models.CharField(max_length=25, verbose_name="Номер")),
                (
                    "price",
                    models.FloatField(max_length=25, verbose_name="Цена договора"),
                ),
                ("date", models.DateField(verbose_name="Дата договора")),
            ],
        ),
    ]
