# Generated by Django 4.1.7 on 2023-02-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0002_rename_contract_contracts_alter_contracts_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Название")),
                ("number", models.CharField(max_length=25, verbose_name="Номер")),
                ("price", models.FloatField(max_length=25, verbose_name="Цена акта")),
                ("date", models.DateField(verbose_name="Дата акта")),
            ],
            options={"verbose_name": "Акт", "verbose_name_plural": "Акты",},
        ),
    ]
