# Generated by Django 4.1.7 on 2023-02-25 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0003_acts"),
    ]

    operations = [
        migrations.AddField(
            model_name="acts",
            name="contract",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="archive.contracts",
            ),
        ),
        migrations.AlterField(
            model_name="acts",
            name="number",
            field=models.CharField(max_length=25, unique=True, verbose_name="Номер"),
        ),
        migrations.AlterField(
            model_name="contracts",
            name="number",
            field=models.CharField(max_length=25, unique=True, verbose_name="Номер"),
        ),
    ]
