# Generated by Django 4.1.7 on 2023-02-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0004_acts_contract_alter_acts_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Companies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=120, verbose_name="Название акта"),
                ),
                (
                    "inn",
                    models.IntegerField(max_length=25, unique=True, verbose_name="ИНН"),
                ),
            ],
            options={"verbose_name": "Компания", "verbose_name_plural": "Компании",},
        ),
        migrations.AlterField(
            model_name="acts",
            name="number",
            field=models.CharField(
                max_length=25, unique=True, verbose_name="Номер акта"
            ),
        ),
        migrations.AlterField(
            model_name="acts",
            name="title",
            field=models.CharField(max_length=120, verbose_name="Название акта"),
        ),
        migrations.AddField(
            model_name="contracts",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="archive.companies",
            ),
        ),
    ]
